---
title: "Historical background and revision"
---
The  original  version  of  the  Methodological  Framework  used  in Displacement  Tracking  Operations  for  Quantifying  Displacement  and Mobility  (MFQDM)  was  published  on  December  5^th^  2017.  It  was  used widely,  both  nationally  and  in  regional  operations,  to  develop  DTM methodologies responsive to information requirements on displacement and  mobility.  Methodological  developments  in  country  missions  have revealed the need for updating the MFQDM. 

The 2022 update reflects latest methodological improvements as well as changes of terminology implemented to facilitate common understanding and coordination with an increasing range of stakeholders. In the MFQDM 2^nd^ edition, sections 2, 6, 7, 8 and 10 remain relatively unchanged, whereas section 9 has been largely expanded which reflects an increased in available published DTM Standards for DTM[^1] systems, outputs and operations as well as protocols for sharing sensitive information. *Section 1 – ‘Historical background and revision’* was not in the original version and is new. 

*Section  4*  includes  an  important  update  on  terminology.  DTM  tools within  the  Mobility Tracking  component,  previously  recognized  as baseline location assessment and site assessment have been increasingly implemented in a diversity of geographical units. To reflect this change designation  was  changed  to  Baseline  Sub-Area  Assessment  (previously Baseline Location Assessment) and Multi-Sectoral Location Assessments (previously Site Assessment) to acknowledge the multi-sector nature of the assessments. 

*Section  5*  reflects  the  changes  in  terminology  mentioned  above  to Mobility Tracking tools and aligns minimum fields for data collection in Registration  with  the  DTM  data  dictionary  (for  more  information  on the  Data  Dictionary,  please  see  Section  7).  Within  the  more  detailed table on registration (section 5.3) there are minor changes, including the reference  to  cash  assistance  as  the  programmatic  area  supported  by registration. The Points of Entry (PoE) monitoring has also been added which was developed and scaled throughout the COVID-19 pandemic (section 5.2.4).

[^1]: DTM Standards include: Artificial Intelligence (AI), data science & ethics, Data analysis planning, Data archiving, recovery & destruction, Data design and collection, Data protection & privacy, Data sharing, Data visualisation, Geospatial information, Internal data consolidation, Partnerships & external relationships, Monitoring & evaluation, Project management, Reporting & publication, Sampling and Training & internal capacity building.
