---
title: "Limitations and risks"
---

Data collection methods carry certain limitations and risks, which should be considered and mitigated to the extent possible during the design and implementation of DTM activities. Specific limitations and  risks  associated  with  DTM  tools  and  methods  covered  in this  Framework  are  indicated  throughout  the  various  tables  in the  previous  section.  Limitations  and  risks  may  vary  depending on  the  tools  and  methods  that  are  adapted  or  combined.  The characteristics of a particular implementation approach and any related caveats for analysis or use of the data produced, should be  indicated  in  the  methodology  section  of  DTM  information products. Furthermore, IOM DTM co-authored the Inter-Agency Standing  Committee  (IASC)  Operational  Guidance  on  Data Responsibility in Humanitarian Action,1 providing tools on how to design data activities responsibility.

Given  variations  in  approaches  and  operating  environments,  a risk assessment is recommended when designing a DTM exercise to identify areas of concern specific to the context and ensure mitigation measures are in place throughout implementation.2 This includes  identification  of  potential  risks  for  mobile  populations when  selecting  components,  tools  and  methods  during  the planning  stages,  as  well  as  regular  monitoring  and  adjustments to  minimize  risks  throughout  implementation.  Do  No  Harm  is to be prioritised throughout the entire process, including during analysis of results and sharing of data. Including an explanation of the approach, objectives and limitations of data collection when disseminating DTM products can mitigate the risk of inaccurate or  misleading  data  analysis  by  third  parties,  for  purposes  that undermine the well-being of populations on the move.

In the early stages of a response, provision of the best information possible within the shortest time frame may be prioritized over statistical  robustness  of  data,  in  order  to  produce  an  initial indication  of  population  movements  and  needs  to  kick-start response planning. As access expands and the universe of analysis becomes known with more certainty, DTM exercises will often be  adapted  or  expanded  to  incorporate  additional  tools  and methods,  generating  information  with  greater  validity,  accuracy or precision. Data collection through DTM is repeated in multiple rounds  to  regularly  refresh  and  refine  available  information and  to  adapt  as  needed  to  change  in  the  operational  context or  information  objectives.  Past  implementation  experience has  shown  that  different  components,  tools  and  methods  may become relevant at different stages of an operation and combining elements  can  strengthen  an  approach  and  enrich  the  data  and information produced.