---
title: "DTM partners toolkit"
---

In  2017,  DTM  and  partners  began  operationalizing  the  results from the Grand Bargain work by jointly developing a toolkit that applies the approach developed by the working group to the work of DTM teams and Partners in the field to support cooperation. Partners are those who participate in the humanitarian response, and include Clusters, Sectors, Working Groups (WGs), NGOs, International Organizations,  Authorities,  UN  agencies,  IOM  Programmes  and more.  DTM  has  worked  with  many  Partners,  including  Global CCCM Cluster, Global Child Protection Areas of Responsibilities (AoRs), Global Education Cluster, Global Gender-Based Violence (GBV)  AoR,  Global  Health  Cluster,  Global  Protection  Cluster, Global  Shelter  Cluster,  Global  UNICEF  Cluster  Coordination Team,  Global  WASH  Cluster,  Geneva-based  Cash  Working Group, Global Accountability to Affected Population (AAP) and Protection from Sexual Exploitation and Abuse (PSEA) experts from IOM, the IASC Task Force and Translators Without Borders.

The  common  objective  of  DTM  and  Partners  Toolkit  is  to ensure  that  DTM  collects  data  that  partners  can  use.  After common  challenges  faced  by  field  colleagues  were  identified, DTM  and  Partners  worked  jointly  to  find  ways  to  overcome said challenges. The resulting approach and tools are now in the jointly developed and publicly available DTM & Partners Toolkit (consultable  by  topic:  https://displacement.iom.int/dtm-partners- toolkit/guide, consultable by tools for each step of the  process: https://displacement.iom.int/dtm-partners-toolkit/steps a repository of all tools at: https://displacement.iom.int/dtm-toolkit/ dtm-partners-toolkit).
