---
title: "Survey"
---

In most cases, it is not possible nor necessary to interview every single member of a large population group because it is too costly and time-consuming, therefore a sample survey is used. A survey is a standardized way of using probability to collect information about a target group that produces conclusions that can be deemed representative of the population of interest. DTM’s survey component enriches and complements other DTM activities by providing a deeper understanding of mobile populations (e.g. IDPs, returnees, migrants). Initial survey design should consider geographic areas of interest, populations of interest and indicators of interest in order to identify the most appropriate methodological approach for the context. Depending on information needs and survey objectives, data can be collected using quantitative or qualitative tools; through individual, household or key informant interviews; and random or purposive sampling methodologies. Indicator selection will determine the appropriate type of survey required (quantitative or qualitative) and the primary sampling units (households, individuals, community representatives). Standardized indicators can be sourced from the DTM Data Dictionary (see Section 7 for more information) and adjusted for contextual needs. Where a survey is part of an inter-agency or multi-sectoral response, indicators may need to be agreed and/or validated through mandated coordination groups. DTM technical experts are available to support on indicator selection and design. Through its flow monitoring, mobility tracking and registration components, DTM builds and regularly updates the master-list of locations and information about how population categories are geographically spread. This baseline information can be used to develop a survey’s sampling framework where the populations of interest for the survey are already covered in the master list. Where statistically representative findings are required, random selection of households or individuals per population group is critical in ensuring validity. DTM technical experts support in the development of sample design methods to ensure an unbiased selection that is tailored to the available sample frame data. DTM has experience implementing the following types of survey categories: Return Intention Survey, Displacement Solutions Survey, Migration Flows Survey, Multi-Sectoral Needs Assessment Survey (MSNA), Socio-economic Surveys, Demographic Survey, and Post-return Surveys. Most DTM surveys are deployed to achieve a range of objectives, as a result specific guidance for the surveys mentioned above can be provided by the DTM Global Support team (dtmsupportservices@iom.int). Guidance for Multi-Sectoral Needs Assessments (MSNA) is provided in the Section 5.4.1 as this survey has a fixed objective.

## Multi-Sectoral Needs Assessments (MSNA)

The MSNA survey approach builds on available data on IDP, resident and return presence to provide more comprehensive information on humanitarian and recovery needs, directly from the population of interest. Through mobility tracking and Multi- Sectoral Location Assessments (MSLA), DTM operations are able to provide the population estimates needed for calculating MSNA sample size and sample locations. Using quantitative household interviews, the approach captures characteristics on vulnerabilities and assistance gaps within the target population(s). An MSNA survey allows for detailed metrics on use and awareness of services, disabilities, specific needs, as well as household characteristics that vary too widely to be accurately identified at community level. DTM MSNA aligns with the objectives and indicators of the Joint Intersectoral Analysis Framework (JIAF), under development by the Joint Intersectoral Analysis Group (JIAG). This inter-organizational tool aims to present a unified and standardized approach to collecting and analyzing humanitarian needs data and forms part of the Grand Bargain commitments of the Needs Assessment Workstream.1 MSNAs will usually integrate into the country-level Humanitarian Programme Cycle, specifically to inform the Humanitarian Needs Overview (HNO) and Humanitarian Response Plan (HPC). DTM indicators for all multi-sectoral assessments which have received global endorsement can be found in the DTM Data Dictionary, a centralized repository of DTM questions/indicators and answers. Starting from information needs of partners, DTM will select relevant indicators and develop data collection tools that are appropriate to the context. Further guidance on indicator selection, including selection of data fields, indicators and question can be found in Section 7.